### ISSUE TITLE
automatically enable 404.php page when accessing from edge browser on mobile

### ISSUE THREAD

**Issue by superantim** [theajack/disable-devtool#55] opened 2023-03-10 04:08 UTC
i checked on iphone 13 pro ios version 15.4 using edge browser version 110.0.1587.57
iphone x 15.4 and edge ver 105.0.1343.53 has error too
chrome desktop & laptop is fine, but on mobile ios sometime has error ver 101.0.4951.44
safari is fine
edge on desktop and laptop is fine

if the 404 page is not installed, the site will automatically close, example: https://theajack.github.io/disable-devtool/ open on edge mobile ios

my setting:
`<script disable-devtool-auto url='https://mysite.com/404.php' src='https://cdn.jsdelivr.net/npm/disable-devtool'></script>`

**Comment by theajack** [comment] 2023-03-10 07:22
I also reproduced this problem, I will check the reason later
@superantim

**Comment by theajack** [comment] 2023-03-10 15:59
fixed in v0.3.4

**Closed by theajack** 2023-03-10 15:59 UTC
