### ISSUE TITLE
对窗口大小的检测方法会误伤侧边栏

### ISSUE THREAD

**Issue by daidr** [theajack/disable-devtool#23] opened 2022-01-13 09:18 UTC
会误伤下面这些情况：
1.Edge的垂直标签页功能开启时
2.任一侧边栏打开时（比如将下载浮窗固定到侧边栏）

**Comment by theajack** [comment] 2022-01-13 16:04
感谢您的反馈 会在后续版本中修复
@daidr

**Comment by JorgeGNL** [comment] 2022-02-08 15:27
Hi,

Is there any fix for this issue, some users using Edge are having problems when having the vertical tab enabled?

Please share an update with the fix.

Thanks.

**Comment by theajack** [comment] 2022-02-09 00:57
@daidr @JorgeGNL 
已修复，请升级到到0.2.3使用
Fixed，Please update to v0.2.3

**Closed by theajack** 2022-02-09 00:57 UTC

**Comment by JorgeGNL** [comment] 2022-02-09 14:28
The issue is still not resolved on v0.2.3.

Let's wait, if others also have the same issue as me.
